# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'WGMaplyGPkgTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GeoPackageWGTest
  pod 'geopackage-ios', :git => 'https://github.com/mousebird/geopackage-ios.git', :branch => 'develop'

end
